import "./global.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#04364A] text-white px-4 min-h-[100vh] flex flex-col justify-between items-center w-full`}
      >
        <Header />
        <main className="flex flex-col justify-between items-center w-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
