import Search from "@/components/Search";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <Search />
    </>
  );
};

export default Home;
